export * from '@/components/molecules/card-hero/card-hero';
export * from '@/components/molecules/search-home/search-home';
export * from '@/components/molecules/search-details/search-details';
export * from '@/components/molecules/favorite-hero/favorite-hero';
export * from '@/components/molecules/order-by-name/order-by-name';
export * from '@/components/molecules/total-hero/total-hero';
export * from '@/components/molecules/description-hero/description-hero';
export * from '@/components/molecules/info-section/info-section';
export * from '@/components/molecules/card-comic/card-comic';
