export * from '../molecules/card-hero/card-hero';
export * from '../molecules/search-home/search-home';
export * from '../molecules/search-details/search-details';
export * from '../molecules/favorite-hero/favorite-hero';
export * from '../molecules/order-by-name/order-by-name';
export * from '../molecules/total-hero/total-hero';
export * from '../molecules/description-hero/description-hero';
export * from '../molecules/info-section/info-section';
export * from '../molecules/card-comic/card-comic';
